name: CI/CD Vercel Deploy v2

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Vercel CLI
        run: npm install -g vercel

      - name: Pull das configs do Vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build do projeto
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy no Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}